package app

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS schools (
		id VARCHAR(40) PRIMARY KEY,
		name VARCHAR(100) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS campuses (
		id VARCHAR(40) PRIMARY KEY,
		school_id VARCHAR(40) NOT NULL,
		name VARCHAR(100) NOT NULL,
		address VARCHAR(255) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		INDEX idx_campuses_school (school_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS grades (
		id VARCHAR(40) PRIMARY KEY,
		school_id VARCHAR(40) NOT NULL,
		name VARCHAR(40) NOT NULL,
		stage VARCHAR(40) DEFAULT '',
		sort_order INT NOT NULL DEFAULT 0,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		UNIQUE KEY uk_grades_school_name (school_id, name)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS classes (
		id VARCHAR(40) PRIMARY KEY,
		school_id VARCHAR(40) NOT NULL,
		campus_id VARCHAR(40) DEFAULT '',
		grade_id VARCHAR(40) DEFAULT '',
		name VARCHAR(100) NOT NULL,
		grade VARCHAR(40) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		INDEX idx_classes_school (school_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS users (
		id VARCHAR(40) PRIMARY KEY,
		school_id VARCHAR(40) NOT NULL,
		display_name VARCHAR(80) NOT NULL,
		mobile VARCHAR(40) DEFAULT '',
		email VARCHAR(120) DEFAULT '',
		status VARCHAR(30) NOT NULL DEFAULT 'active',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		INDEX idx_users_school (school_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS roles (
		id VARCHAR(40) PRIMARY KEY,
		name VARCHAR(80) NOT NULL,
		scope VARCHAR(40) NOT NULL DEFAULT 'school',
		permissions_json JSON NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		UNIQUE KEY uk_roles_name_scope (name, scope)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS user_roles (
		user_id VARCHAR(40) NOT NULL,
		role_id VARCHAR(40) NOT NULL,
		org_type VARCHAR(40) NOT NULL DEFAULT 'school',
		org_id VARCHAR(40) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (user_id, role_id, org_id),
		INDEX idx_user_roles_role (role_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS students (
		id VARCHAR(40) PRIMARY KEY,
		user_id VARCHAR(40) DEFAULT '',
		class_id VARCHAR(40) NOT NULL,
		student_no VARCHAR(40) DEFAULT '',
		name VARCHAR(80) NOT NULL,
		guardian_name VARCHAR(80) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		INDEX idx_students_class (class_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS guardians (
		id VARCHAR(40) PRIMARY KEY,
		user_id VARCHAR(40) DEFAULT '',
		name VARCHAR(80) NOT NULL,
		mobile VARCHAR(40) DEFAULT '',
		relationship VARCHAR(40) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS student_guardians (
		student_id VARCHAR(40) NOT NULL,
		guardian_id VARCHAR(40) NOT NULL,
		relationship VARCHAR(40) DEFAULT '',
		is_primary BOOLEAN NOT NULL DEFAULT FALSE,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (student_id, guardian_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS teachers (
		id VARCHAR(40) PRIMARY KEY,
		user_id VARCHAR(40) DEFAULT '',
		school_id VARCHAR(40) NOT NULL,
		name VARCHAR(80) NOT NULL,
		subject VARCHAR(40) NOT NULL,
		role VARCHAR(40) DEFAULT 'subject_teacher',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		INDEX idx_teachers_school (school_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS teacher_classes (
		teacher_id VARCHAR(40) NOT NULL,
		class_id VARCHAR(40) NOT NULL,
		subject VARCHAR(40) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (teacher_id, class_id, subject)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS subjects (
		id VARCHAR(40) PRIMARY KEY,
		school_id VARCHAR(40) NOT NULL,
		name VARCHAR(60) NOT NULL,
		code VARCHAR(40) DEFAULT '',
		status VARCHAR(30) NOT NULL DEFAULT 'active',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		UNIQUE KEY uk_subjects_school_name (school_id, name),
		INDEX idx_subjects_school (school_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS class_subjects (
		id VARCHAR(40) PRIMARY KEY,
		school_id VARCHAR(40) NOT NULL,
		grade_id VARCHAR(40) NOT NULL,
		class_id VARCHAR(40) NOT NULL,
		subject_id VARCHAR(40) NOT NULL,
		teacher_id VARCHAR(40) DEFAULT '',
		status VARCHAR(30) NOT NULL DEFAULT 'active',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		UNIQUE KEY uk_class_subject (class_id, subject_id),
		INDEX idx_class_subjects_school (school_id, grade_id),
		INDEX idx_class_subjects_teacher (teacher_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS teacher_grades (
		teacher_id VARCHAR(40) NOT NULL,
		grade_id VARCHAR(40) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (teacher_id, grade_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS teacher_subjects (
		teacher_id VARCHAR(40) NOT NULL,
		subject_id VARCHAR(40) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (teacher_id, subject_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS guardian_invitations (
		id VARCHAR(40) PRIMARY KEY,
		student_id VARCHAR(40) NOT NULL,
		teacher_id VARCHAR(40) NOT NULL,
		token_hash CHAR(64) NOT NULL,
		mobile_hint VARCHAR(40) DEFAULT '',
		status VARCHAR(30) NOT NULL DEFAULT 'pending',
		expires_at DATETIME NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		UNIQUE KEY uk_guardian_invitation_token (token_hash),
		INDEX idx_guardian_invitations_student (student_id, status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS guardian_certifications (
		id VARCHAR(40) PRIMARY KEY,
		invitation_id VARCHAR(40) NOT NULL,
		student_id VARCHAR(40) NOT NULL,
		guardian_id VARCHAR(40) NOT NULL,
		relationship VARCHAR(40) NOT NULL,
		evidence_object_key VARCHAR(255) DEFAULT '',
		status VARCHAR(30) NOT NULL DEFAULT 'pending',
		reviewer_id VARCHAR(40) DEFAULT '',
		review_note VARCHAR(255) DEFAULT '',
		submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		reviewed_at DATETIME NULL,
		UNIQUE KEY uk_guardian_certification_pair (student_id, guardian_id),
		INDEX idx_guardian_certifications_status (status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS ai_capability_requests (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		capability VARCHAR(60) NOT NULL,
		user_id VARCHAR(40) DEFAULT '',
		student_id VARCHAR(40) NOT NULL,
		channel VARCHAR(40) NOT NULL DEFAULT 'portal',
		status VARCHAR(30) NOT NULL DEFAULT 'waitlisted',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		INDEX idx_ai_capability_requests_student (student_id, capability)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS knowledge_points (
		id VARCHAR(40) PRIMARY KEY,
		school_id VARCHAR(40) DEFAULT '',
		grade_id VARCHAR(40) DEFAULT '',
		subject_id VARCHAR(40) DEFAULT '',
		name VARCHAR(100) NOT NULL,
		subject VARCHAR(40) NOT NULL,
		parent_id VARCHAR(40) NULL,
		code VARCHAR(80) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		UNIQUE KEY uk_knowledge_name_subject (name, subject)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS question_bank (
		id VARCHAR(40) PRIMARY KEY,
		school_id VARCHAR(40) DEFAULT '',
		grade_id VARCHAR(40) DEFAULT '',
		subject_id VARCHAR(40) DEFAULT '',
		subject VARCHAR(40) NOT NULL,
		question_type VARCHAR(40) NOT NULL,
		difficulty VARCHAR(40) NOT NULL DEFAULT 'medium',
		content TEXT NOT NULL,
		answer TEXT,
		analysis TEXT,
		source VARCHAR(40) NOT NULL DEFAULT 'manual',
		status VARCHAR(30) NOT NULL DEFAULT 'active',
		created_by VARCHAR(40) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		INDEX idx_question_bank_subject_grade (subject, grade_id),
		INDEX idx_question_bank_type_difficulty (question_type, difficulty)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS question_bank_knowledge_points (
		question_id VARCHAR(40) NOT NULL,
		knowledge_point_id VARCHAR(40) NOT NULL,
		knowledge_point_name VARCHAR(100) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (question_id, knowledge_point_id),
		INDEX idx_question_bank_knowledge (knowledge_point_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS paper_compositions (
		id VARCHAR(40) PRIMARY KEY,
		title VARCHAR(120) NOT NULL,
		school_id VARCHAR(40) DEFAULT '',
		grade_id VARCHAR(40) DEFAULT '',
		grade_name VARCHAR(80) DEFAULT '',
		subject_id VARCHAR(40) DEFAULT '',
		subject VARCHAR(40) NOT NULL,
		mode VARCHAR(40) NOT NULL DEFAULT 'manual',
		status VARCHAR(30) NOT NULL DEFAULT 'draft',
		question_count INT NOT NULL DEFAULT 0,
		total_score DECIMAL(8,2) NOT NULL DEFAULT 0,
		created_by VARCHAR(40) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		INDEX idx_paper_compositions_subject (subject, grade_id, status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS paper_composition_questions (
		composition_id VARCHAR(40) NOT NULL,
		question_id VARCHAR(40) NOT NULL,
		sort_order INT NOT NULL DEFAULT 0,
		score DECIMAL(6,2) NOT NULL DEFAULT 0,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (composition_id, question_id),
		INDEX idx_composition_questions_question (question_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS ai_tasks (
		id VARCHAR(40) PRIMARY KEY,
		task_type VARCHAR(60) NOT NULL,
		status VARCHAR(30) NOT NULL DEFAULT 'pending',
		provider VARCHAR(80) DEFAULT 'third_party_reserved',
		request_json JSON NOT NULL,
		result_json JSON NULL,
		source_object_key VARCHAR(255) DEFAULT '',
		source_url VARCHAR(255) DEFAULT '',
		owner_type VARCHAR(40) DEFAULT '',
		owner_id VARCHAR(40) DEFAULT '',
		created_by VARCHAR(40) DEFAULT '',
		error_message VARCHAR(255) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		INDEX idx_ai_tasks_owner (owner_type, owner_id),
		INDEX idx_ai_tasks_type_status (task_type, status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS question_types (
		id VARCHAR(40) PRIMARY KEY,
		name VARCHAR(80) NOT NULL,
		mode VARCHAR(40) NOT NULL,
		default_score DECIMAL(6,2) NOT NULL DEFAULT 0,
		auto_gradable BOOLEAN NOT NULL DEFAULT FALSE,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		UNIQUE KEY uk_question_types_name (name)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS paper_templates (
		id VARCHAR(40) PRIMARY KEY,
		name VARCHAR(120) NOT NULL,
		subject VARCHAR(40) NOT NULL,
		grade VARCHAR(40) NOT NULL,
			question_count INT NOT NULL,
			total_score INT NOT NULL,
			source_file_url VARCHAR(255) DEFAULT '',
			status VARCHAR(30) NOT NULL DEFAULT 'draft',
			version INT NOT NULL DEFAULT 1,
			parent_id VARCHAR(40) DEFAULT '',
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS question_templates (
		id VARCHAR(40) PRIMARY KEY,
		template_id VARCHAR(40) NOT NULL,
		question_no VARCHAR(20) NOT NULL,
		question_type VARCHAR(40) NOT NULL,
			score DECIMAL(6,2) NOT NULL,
			standard_answer TEXT,
			scoring_rules_json JSON NULL,
			knowledge_json JSON NOT NULL,
		page_no INT NOT NULL,
		x INT NOT NULL,
		y INT NOT NULL,
		width INT NOT NULL,
		height INT NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		INDEX idx_question_template (template_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS assignments (
		id VARCHAR(40) PRIMARY KEY,
		exam_id VARCHAR(40) DEFAULT '',
		title VARCHAR(120) NOT NULL,
		kind VARCHAR(40) NOT NULL DEFAULT 'exam',
		class_id VARCHAR(40) DEFAULT '',
		class_name VARCHAR(100) NOT NULL,
		template_id VARCHAR(40) NULL,
		template_version INT NOT NULL DEFAULT 1,
		teacher_id VARCHAR(40) DEFAULT '',
		published_at DATETIME NULL,
		due_at DATETIME NULL,
		completed_at DATETIME NULL,
		status VARCHAR(30) NOT NULL DEFAULT 'open',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		INDEX idx_assignments_class (class_name)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS exams (
		id VARCHAR(40) PRIMARY KEY,
		school_id VARCHAR(40) NOT NULL,
		name VARCHAR(120) NOT NULL,
		subject VARCHAR(40) NOT NULL,
		grade VARCHAR(40) NOT NULL,
		template_id VARCHAR(40) DEFAULT '',
		template_version INT NOT NULL DEFAULT 1,
		status VARCHAR(30) NOT NULL DEFAULT 'draft',
		started_at DATETIME NULL,
		ended_at DATETIME NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		INDEX idx_exams_school_status (school_id, status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS assignment_classes (
		assignment_id VARCHAR(40) NOT NULL,
		class_id VARCHAR(40) NOT NULL,
		class_name VARCHAR(100) NOT NULL,
		publish_status VARCHAR(30) NOT NULL DEFAULT 'published',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (assignment_id, class_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS scan_jobs (
		id VARCHAR(40) PRIMARY KEY,
		assignment_id VARCHAR(40) DEFAULT '',
		scan_type VARCHAR(30) NOT NULL DEFAULT 'answer_sheet',
		title VARCHAR(120) NOT NULL,
		class_name VARCHAR(100) NOT NULL,
		template_id VARCHAR(40) DEFAULT '',
		template_version INT NOT NULL DEFAULT 1,
		created_by VARCHAR(40) DEFAULT '',
		pages INT NOT NULL,
		notes TEXT,
		files_json JSON NULL,
		status VARCHAR(60) NOT NULL,
		progress INT NOT NULL DEFAULT 0,
		failure_reason TEXT,
		retry_count INT NOT NULL DEFAULT 0,
		queue_status VARCHAR(30) NOT NULL DEFAULT 'pending',
		queue_message VARCHAR(255) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS scan_task_logs (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		task_id VARCHAR(40) NOT NULL,
		file_key VARCHAR(255) DEFAULT '',
		action VARCHAR(40) NOT NULL,
		message VARCHAR(255) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		INDEX idx_scan_task_logs_task (task_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS worker_task_results (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		task_id VARCHAR(40) NOT NULL,
		status VARCHAR(60) NOT NULL,
		progress INT NOT NULL DEFAULT 0,
		failure_reason TEXT,
		model_version VARCHAR(80) DEFAULT '',
		result_json JSON NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		UNIQUE KEY uk_worker_task_results_task (task_id),
		INDEX idx_worker_task_results_status (status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS submissions (
		id VARCHAR(40) PRIMARY KEY,
		assignment_id VARCHAR(40) NOT NULL,
		student_id VARCHAR(40) NOT NULL,
		scan_task_id VARCHAR(40) DEFAULT '',
		student_name VARCHAR(80) DEFAULT '',
		class_name VARCHAR(100) DEFAULT '',
		file_url VARCHAR(255) NOT NULL,
		page_count INT NOT NULL DEFAULT 0,
		matched_status VARCHAR(30) NOT NULL DEFAULT 'matched',
		status VARCHAR(30) NOT NULL DEFAULT 'uploaded',
		submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		graded_at DATETIME NULL,
		INDEX idx_submissions_assignment (assignment_id),
		INDEX idx_submissions_student (student_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS student_answers (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		submission_id VARCHAR(40) NOT NULL,
		question_id VARCHAR(40) NOT NULL,
		question_no VARCHAR(20) NOT NULL,
		answer_text TEXT,
		answer_json JSON NULL,
		image_url VARCHAR(255) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		UNIQUE KEY uk_student_answers_submission_question (submission_id, question_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS ocr_results (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		submission_id VARCHAR(40) NOT NULL,
		question_id VARCHAR(40) DEFAULT '',
		object_key VARCHAR(255) DEFAULT '',
		text TEXT NOT NULL,
		confidence INT NOT NULL DEFAULT 0,
		blocks_json JSON NULL,
		provider VARCHAR(40) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		INDEX idx_ocr_submission (submission_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS objective_grades (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		submission_id VARCHAR(40) NOT NULL,
		question_id VARCHAR(40) NOT NULL,
		student_answer VARCHAR(255) DEFAULT '',
		correct_answer VARCHAR(255) DEFAULT '',
		score DECIMAL(6,2) NOT NULL DEFAULT 0,
		max_score DECIMAL(6,2) NOT NULL DEFAULT 0,
		is_correct BOOLEAN NOT NULL DEFAULT FALSE,
		confidence INT NOT NULL DEFAULT 0,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		UNIQUE KEY uk_objective_grades_submission_question (submission_id, question_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS objective_review_exceptions (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		submission_id VARCHAR(40) NOT NULL,
		question_id VARCHAR(40) NOT NULL,
		question_no VARCHAR(20) NOT NULL,
		student_answer VARCHAR(255) DEFAULT '',
		confidence INT NOT NULL DEFAULT 0,
		reason VARCHAR(255) NOT NULL,
		status VARCHAR(30) NOT NULL DEFAULT 'pending',
		suggested_score DECIMAL(6,2) NOT NULL DEFAULT 0,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		UNIQUE KEY uk_objective_exception_submission_question (submission_id, question_id),
		INDEX idx_objective_exception_status (status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS subjective_reviews (
		id VARCHAR(40) PRIMARY KEY,
		submission_id VARCHAR(40) NOT NULL,
		question_id VARCHAR(40) NOT NULL,
		paper_name VARCHAR(120) NOT NULL,
		student_name VARCHAR(80) NOT NULL,
		class_name VARCHAR(100) NOT NULL,
		question_no VARCHAR(20) NOT NULL,
		full_score DECIMAL(6,2) NOT NULL,
		standard_answer TEXT NOT NULL,
		scoring_rules_json JSON NOT NULL,
		knowledge_json JSON NOT NULL,
		student_ocr_text TEXT NOT NULL,
		student_image_url VARCHAR(255) DEFAULT '',
		ai_score DECIMAL(6,2) NOT NULL,
		ai_reason TEXT NOT NULL,
		ai_comments_json JSON NOT NULL,
		confidence INT NOT NULL,
		status VARCHAR(30) NOT NULL DEFAULT 'pending',
		review_stage VARCHAR(40) NOT NULL DEFAULT 'first_review',
		assignee_id VARCHAR(40) DEFAULT '',
		priority INT NOT NULL DEFAULT 0,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		UNIQUE KEY uk_review_submission_question (submission_id, question_id),
		INDEX idx_subjective_reviews_status (status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS grading_decisions (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		submission_id VARCHAR(40) NOT NULL,
		question_id VARCHAR(40) NOT NULL,
		final_score DECIMAL(6,2) NOT NULL,
		decision VARCHAR(40) NOT NULL,
		teacher_note TEXT,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		UNIQUE KEY uk_decision_submission_question (submission_id, question_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS question_scores (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		submission_id VARCHAR(40) NOT NULL,
		question_id VARCHAR(40) NOT NULL,
		question_no VARCHAR(20) NOT NULL,
		score DECIMAL(6,2) NOT NULL DEFAULT 0,
		max_score DECIMAL(6,2) NOT NULL DEFAULT 0,
		source VARCHAR(40) NOT NULL DEFAULT 'teacher',
		status VARCHAR(30) NOT NULL DEFAULT 'final',
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		UNIQUE KEY uk_question_scores_submission_question (submission_id, question_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS grading_history (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		submission_id VARCHAR(40) NOT NULL,
		question_id VARCHAR(40) NOT NULL,
		action VARCHAR(40) NOT NULL,
		score DECIMAL(6,2) NOT NULL DEFAULT 0,
		note TEXT,
		actor_id VARCHAR(40) DEFAULT '',
		actor_name VARCHAR(80) DEFAULT '',
		review_stage VARCHAR(40) DEFAULT 'first_review',
		model_version VARCHAR(80) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		INDEX idx_grading_history_submission (submission_id, question_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS wrong_questions (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		student_id VARCHAR(40) NOT NULL,
		question_id VARCHAR(40) NOT NULL,
		submission_id VARCHAR(40) DEFAULT '',
		question_no VARCHAR(20) DEFAULT '',
		knowledge_point_id VARCHAR(40) DEFAULT '',
		knowledge_point VARCHAR(100) NOT NULL,
		error_type VARCHAR(40) NOT NULL DEFAULT 'other',
		wrong_reason VARCHAR(255) NOT NULL,
		source_paper VARCHAR(120) NOT NULL,
		original_question TEXT,
		score DECIMAL(6,2) NOT NULL DEFAULT 0,
		max_score DECIMAL(6,2) NOT NULL DEFAULT 0,
		correct_answer TEXT,
		student_answer TEXT,
		answer_image_url VARCHAR(255) DEFAULT '',
		explanation TEXT,
		correction_status VARCHAR(30) NOT NULL DEFAULT 'pending',
		repractice_status VARCHAR(30) NOT NULL DEFAULT 'not_assigned',
		corrected_at DATETIME NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		UNIQUE KEY uk_wrong_question_submission_question (submission_id, question_id),
		INDEX idx_wrong_student (student_id),
		INDEX idx_wrong_knowledge (knowledge_point)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS wrong_question_knowledge_points (
		wrong_question_id BIGINT NOT NULL,
		knowledge_point_id VARCHAR(40) NOT NULL,
		knowledge_point_name VARCHAR(100) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (wrong_question_id, knowledge_point_id),
		INDEX idx_wrong_question_knowledge (knowledge_point_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS repractice_tasks (
		id VARCHAR(40) PRIMARY KEY,
		title VARCHAR(120) NOT NULL,
		class_name VARCHAR(100) DEFAULT '',
		wrong_question_ids_json JSON NOT NULL,
		knowledge_json JSON NOT NULL,
		status VARCHAR(30) NOT NULL DEFAULT 'assigned',
		due_at DATETIME NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS knowledge_mastery_history (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		class_name VARCHAR(100) NOT NULL,
		student_id VARCHAR(40) DEFAULT '',
		knowledge_point VARCHAR(100) NOT NULL,
		mastery INT NOT NULL,
		wrong_count INT NOT NULL DEFAULT 0,
		student_count INT NOT NULL DEFAULT 0,
		recorded_at DATE NOT NULL,
		UNIQUE KEY uk_mastery_scope_date (class_name, student_id, knowledge_point, recorded_at),
		INDEX idx_mastery_knowledge (knowledge_point, recorded_at)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS object_files (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		object_key VARCHAR(255) NOT NULL,
		bucket VARCHAR(120) DEFAULT '',
		storage_driver VARCHAR(40) NOT NULL DEFAULT 'local',
		url VARCHAR(255) NOT NULL,
		content_type VARCHAR(120) DEFAULT '',
		size_bytes BIGINT NOT NULL DEFAULT 0,
		purpose VARCHAR(40) NOT NULL,
		owner_type VARCHAR(40) DEFAULT '',
		owner_id VARCHAR(40) DEFAULT '',
		metadata_json JSON NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		UNIQUE KEY uk_object_files_key (object_key),
		INDEX idx_object_files_owner (owner_type, owner_id),
		INDEX idx_object_files_purpose (purpose)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS answer_sheet_uploads (
		id VARCHAR(40) PRIMARY KEY,
		composition_id VARCHAR(40) DEFAULT '',
		student_id VARCHAR(40) DEFAULT '',
		student_name VARCHAR(80) DEFAULT '',
		object_key VARCHAR(255) NOT NULL,
		url VARCHAR(255) NOT NULL,
		status VARCHAR(30) NOT NULL DEFAULT 'uploaded',
		grading_task_id VARCHAR(40) DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		INDEX idx_answer_sheet_composition (composition_id),
		INDEX idx_answer_sheet_student (student_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS exam_scores (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		student_name VARCHAR(80) NOT NULL,
		class_name VARCHAR(100) NOT NULL,
		paper_name VARCHAR(120) NOT NULL,
		score DECIMAL(6,2) NOT NULL,
		exam_at DATE NOT NULL,
		UNIQUE KEY uk_exam_scores_seed (student_name, class_name, paper_name, exam_at),
		INDEX idx_exam_scores_class (class_name)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS question_stats (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		paper_name VARCHAR(120) NOT NULL,
		question_no VARCHAR(20) NOT NULL,
		question_type VARCHAR(40) NOT NULL,
		accuracy INT NOT NULL,
		UNIQUE KEY uk_question_stats (paper_name, question_no)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS knowledge_stats (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		name VARCHAR(100) NOT NULL,
		accuracy INT NOT NULL,
		wrong_count INT NOT NULL,
		UNIQUE KEY uk_knowledge_stats_name (name)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS student_risks (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		student_name VARCHAR(80) NOT NULL,
		risk VARCHAR(255) NOT NULL,
		weakness_json JSON NOT NULL,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		UNIQUE KEY uk_student_risks_student_risk (student_name, risk)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS homework_watch (
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		student_name VARCHAR(80) NOT NULL,
		class_name VARCHAR(100) NOT NULL,
		missing INT NOT NULL,
		guardian VARCHAR(80) NOT NULL,
		UNIQUE KEY uk_homework_watch_student (student_name, class_name)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
}

var schemaPatchStatements = []string{
	`ALTER TABLE paper_templates MODIFY COLUMN status VARCHAR(30) NOT NULL DEFAULT 'draft'`,
	`UPDATE paper_templates SET status = 'published' WHERE status = 'ready'`,
}

var seedStatements = []string{
	`INSERT IGNORE INTO schools (id, name) VALUES ('school_001', '示范学校')`,
	`INSERT IGNORE INTO campuses (id, school_id, name, address) VALUES ('campus_main', 'school_001', '主校区', '示范路 1 号')`,
	`INSERT IGNORE INTO grades (id, school_id, name, stage, sort_order) VALUES ('grade_6', 'school_001', '六年级', 'primary', 6)`,
	`INSERT IGNORE INTO roles (id, name, scope, permissions_json) VALUES
		('role_admin', '教务管理员', 'school', JSON_ARRAY('dashboard:read', 'template:write', 'grading:write')),
		('role_teacher', '任课教师', 'class', JSON_ARRAY('assignment:write', 'grading:write', 'analytics:read')),
		('role_guardian', '家长', 'student', JSON_ARRAY('student:read', 'wrong-question:read'))`,
	`INSERT IGNORE INTO users (id, school_id, display_name, mobile, email, status) VALUES
		('user_teacher_001', 'school_001', '陈老师', '13800000001', 'teacher@example.local', 'active'),
		('user_stu_001', 'school_001', '张三', '', '', 'active'),
		('user_stu_002', 'school_001', '李四', '', '', 'active'),
		('user_stu_003', 'school_001', '赵六', '', '', 'active'),
		('user_guardian_001', 'school_001', '张三家长', '13800000011', '', 'active'),
		('user_guardian_002', 'school_001', '李四家长', '13800000012', '', 'active'),
		('user_guardian_003', 'school_001', '赵六家长', '13800000013', '', 'active')`,
	`INSERT IGNORE INTO user_roles (user_id, role_id, org_type, org_id) VALUES
		('user_teacher_001', 'role_teacher', 'class', 'class_603'),
		('user_guardian_001', 'role_guardian', 'student', 'stu_001'),
		('user_guardian_002', 'role_guardian', 'student', 'stu_002'),
		('user_guardian_003', 'role_guardian', 'student', 'stu_003')`,
	`INSERT IGNORE INTO classes (id, school_id, campus_id, grade_id, name, grade) VALUES ('class_603', 'school_001', 'campus_main', 'grade_6', '六年级 3 班', '六年级')`,
	`INSERT IGNORE INTO teachers (id, user_id, school_id, name, subject, role) VALUES ('teacher_001', 'user_teacher_001', 'school_001', '陈老师', '数学', 'subject_teacher')`,
	`INSERT IGNORE INTO teacher_classes (teacher_id, class_id, subject) VALUES ('teacher_001', 'class_603', '数学')`,
	`INSERT IGNORE INTO subjects (id, school_id, name, code) VALUES
		('subject_math', 'school_001', '数学', 'math'),
		('subject_chinese', 'school_001', '语文', 'chinese'),
		('subject_english', 'school_001', '英语', 'english')`,
	`INSERT IGNORE INTO class_subjects (id, school_id, grade_id, class_id, subject_id, teacher_id) VALUES
		('course_603_math', 'school_001', 'grade_6', 'class_603', 'subject_math', 'teacher_001')`,
	`INSERT IGNORE INTO teacher_grades (teacher_id, grade_id) VALUES ('teacher_001', 'grade_6')`,
	`INSERT IGNORE INTO teacher_subjects (teacher_id, subject_id) VALUES ('teacher_001', 'subject_math')`,
	`INSERT IGNORE INTO guardians (id, user_id, name, mobile, relationship) VALUES
		('guardian_001', 'user_guardian_001', '张三家长', '13800000011', 'parent'),
		('guardian_002', 'user_guardian_002', '李四家长', '13800000012', 'parent'),
		('guardian_003', 'user_guardian_003', '赵六家长', '13800000013', 'parent')`,
	`INSERT IGNORE INTO students (id, user_id, class_id, student_no, name, guardian_name) VALUES
		('stu_001', 'user_stu_001', 'class_603', '60301', '张三', '张三家长'),
		('stu_002', 'user_stu_002', 'class_603', '60302', '李四', '李四家长'),
		('stu_003', 'user_stu_003', 'class_603', '60303', '赵六', '赵六家长')`,
	`INSERT IGNORE INTO student_guardians (student_id, guardian_id, relationship, is_primary) VALUES
		('stu_001', 'guardian_001', 'parent', TRUE),
		('stu_002', 'guardian_001', 'parent', FALSE),
		('stu_002', 'guardian_002', 'parent', TRUE),
		('stu_003', 'guardian_003', 'parent', TRUE)`,
	`INSERT IGNORE INTO knowledge_points (id, school_id, grade_id, subject_id, name, subject, code) VALUES
		('kp_001', 'school_001', 'grade_6', 'subject_math', '分数应用题', '数学', 'math_fraction_application'),
		('kp_002', 'school_001', 'grade_6', 'subject_math', '几何面积', '数学', 'math_geometry_area'),
		('kp_003', 'school_001', 'grade_6', 'subject_math', '比例换算', '数学', 'math_ratio_conversion'),
		('kp_004', 'school_001', 'grade_6', 'subject_math', '比例', '数学', 'math_ratio'),
		('kp_005', 'school_001', 'grade_6', 'subject_math', '分数', '数学', 'math_fraction')`,
	`INSERT IGNORE INTO question_types (id, name, mode, default_score, auto_gradable) VALUES
		('qt_single_choice', 'single_choice', 'objective', 2, TRUE),
		('qt_fill_blank', 'fill_blank', 'objective', 3, TRUE),
		('qt_subjective', 'subjective', 'subjective', 10, FALSE)`,
	`INSERT INTO paper_templates (id, name, subject, grade, question_count, total_score, source_file_url, status, version, parent_id) VALUES
		('tpl_001', '六年级数学期中卷', '数学', '六年级', 25, 100, '/mock/templates/tpl_001-blank-paper.pdf', 'published', 1, '')
		ON DUPLICATE KEY UPDATE
			name = VALUES(name),
			subject = VALUES(subject),
			grade = VALUES(grade),
			question_count = VALUES(question_count),
			total_score = VALUES(total_score),
			source_file_url = VALUES(source_file_url),
			status = VALUES(status),
			version = VALUES(version),
			parent_id = VALUES(parent_id)`,
	`INSERT IGNORE INTO question_templates (id, template_id, question_no, question_type, score, standard_answer, scoring_rules_json, knowledge_json, page_no, x, y, width, height) VALUES
		('q_001', 'tpl_001', '1', 'single_choice', 2, 'A', JSON_ARRAY('选对 A 得 2 分'), JSON_ARRAY('分数'), 1, 120, 260, 480, 80),
		('q_015', 'tpl_001', '15', 'subjective', 10, '先设未知数 x，列出比例关系 3:5 = x:40，解得 x = 24。答：需要 24 千克。', JSON_ARRAY('正确设未知数 2 分', '列出比例关系 4 分', '计算过程正确 2 分', '结果与答语完整 2 分'), JSON_ARRAY('比例', '应用题建模'), 2, 96, 420, 620, 180),
		('q_018', 'tpl_001', '18', 'subjective', 8, '根据面积公式拆分图形并计算。', JSON_ARRAY('拆分图形 2 分', '公式正确 2 分', '计算正确 3 分', '单位完整 1 分'), JSON_ARRAY('几何面积'), 2, 110, 640, 600, 160)
		ON DUPLICATE KEY UPDATE
			question_no = VALUES(question_no),
			question_type = VALUES(question_type),
			score = VALUES(score),
			standard_answer = VALUES(standard_answer),
			scoring_rules_json = VALUES(scoring_rules_json),
			knowledge_json = VALUES(knowledge_json),
			page_no = VALUES(page_no),
			x = VALUES(x),
			y = VALUES(y),
			width = VALUES(width),
			height = VALUES(height)`,
	`INSERT IGNORE INTO question_bank
		(id, school_id, grade_id, subject_id, subject, question_type, difficulty, content, answer, analysis, source, created_by)
	VALUES
		('qb_001', 'school_001', 'grade_6', 'subject_math', '数学', 'single_choice', 'easy', '比较 3/5 和 4/7 的大小，选择正确答案。A. 3/5 > 4/7 B. 3/5 < 4/7 C. 相等 D. 无法比较', 'A', '通分后比较，3/5=21/35，4/7=20/35。', 'template_split', 'teacher_001'),
		('qb_002', 'school_001', 'grade_6', 'subject_math', '数学', 'subjective', 'medium', '一桶油用去 3/5 后还剩 40 千克，这桶油原来有多少千克？', '100 千克', '剩余为 2/5，对应 40 千克，所以总量为 40 ÷ 2/5 = 100。', 'manual', 'teacher_001'),
		('qb_003', 'school_001', 'grade_6', 'subject_math', '数学', 'subjective', 'medium', '将组合图形拆成长方形和三角形后，计算总面积。', '按图形数据分别计算后相加。', '关键是标出拆分依据、公式和单位。', 'template_split', 'teacher_001')`,
	`INSERT IGNORE INTO question_bank_knowledge_points (question_id, knowledge_point_id, knowledge_point_name) VALUES
		('qb_001', 'kp_005', '分数'),
		('qb_002', 'kp_001', '分数应用题'),
		('qb_002', 'kp_004', '比例'),
		('qb_003', 'kp_002', '几何面积')`,
	`INSERT IGNORE INTO exams (id, school_id, name, subject, grade, template_id, template_version, status, started_at, ended_at) VALUES
		('exam_001', 'school_001', '六年级数学期中卷', '数学', '六年级', 'tpl_001', 1, 'published', NOW(), NOW() + INTERVAL 1 DAY)`,
	`INSERT IGNORE INTO assignments (id, exam_id, title, kind, class_id, class_name, template_id, template_version, teacher_id, published_at, due_at, status) VALUES
		('assign_001', 'exam_001', '六年级数学期中卷', 'exam', 'class_603', '六年级 3 班', 'tpl_001', 1, 'teacher_001', NOW(), NOW() + INTERVAL 1 DAY, 'open')`,
	`INSERT IGNORE INTO assignment_classes (assignment_id, class_id, class_name, publish_status) VALUES
		('assign_001', 'class_603', '六年级 3 班', 'published')`,
	`INSERT INTO scan_jobs (id, scan_type, title, class_name, template_id, template_version, pages, status, progress) VALUES
		('scan_001', 'answer_sheet', '六年级数学期中卷', '六年级 3 班', 'tpl_001', 1, 96, 'OCR 识别中', 68),
		('scan_002', 'answer_sheet', '分数应用题专项', '六年级 1 班', 'tpl_001', 1, 42, '等待 OMR', 32),
		('scan_003', 'paper', '几何面积小测空白试卷', '五年级 2 班', '', 1, 48, '试卷已导入', 100)
		ON DUPLICATE KEY UPDATE
			template_id = VALUES(template_id),
			template_version = VALUES(template_version)`,
	`INSERT IGNORE INTO submissions (id, assignment_id, student_id, scan_task_id, student_name, class_name, file_url, page_count, matched_status, status) VALUES
		('sub_001', 'assign_001', 'stu_001', 'scan_001', '张三', '六年级 3 班', '/mock/student-answer-q15.png', 2, 'matched', 'graded'),
		('sub_002', 'assign_001', 'stu_002', 'scan_001', '李四', '六年级 3 班', '/mock/student-answer-q18.png', 2, 'matched', 'uploaded')`,
	`INSERT IGNORE INTO student_answers (submission_id, question_id, question_no, answer_text, image_url) VALUES
		('sub_001', 'q_015', '15', '设需要 x 千克，3/5 = x/40，5x = 120，x = 24。答需要 24 千克。', '/mock/student-answer-q15.png'),
		('sub_002', 'q_018', '18', '把图形看成长方形和三角形，长方形面积 36，三角形面积 12，总面积 48。', '/mock/student-answer-q18.png')`,
	`INSERT IGNORE INTO ocr_results (submission_id, question_id, object_key, text, confidence, blocks_json, provider) VALUES
		('sub_001', 'q_015', 'mock/student-answer-q15.png', '设需要 x 千克，3/5 = x/40，5x = 120，x = 24。答需要 24 千克。', 92, JSON_ARRAY(), 'fixture'),
		('sub_002', 'q_018', 'mock/student-answer-q18.png', '把图形看成长方形和三角形，长方形面积 36，三角形面积 12，总面积 48。', 88, JSON_ARRAY(), 'fixture')`,
	`INSERT IGNORE INTO objective_grades (submission_id, question_id, student_answer, correct_answer, score, max_score, is_correct, confidence) VALUES
		('sub_001', 'q_001', 'A', 'A', 2, 2, TRUE, 98),
		('sub_002', 'q_001', 'B', 'A', 0, 2, FALSE, 94)`,
	`INSERT IGNORE INTO objective_review_exceptions (submission_id, question_id, question_no, student_answer, confidence, reason, status, suggested_score) VALUES
		('sub_002', 'q_001', '1', 'B', 68, '低置信度且答案与标准答案不一致', 'pending', 0)`,
	`INSERT IGNORE INTO subjective_reviews (id, submission_id, question_id, paper_name, student_name, class_name, question_no, full_score, standard_answer, scoring_rules_json, knowledge_json, student_ocr_text, student_image_url, ai_score, ai_reason, ai_comments_json, confidence, status) VALUES
		('review_001', 'sub_001', 'q_015', '六年级数学期中卷', '张三', '六年级 3 班', '15', 10, '先设未知数 x，列出比例关系 3:5 = x:40，解得 x = 24。答：需要 24 千克。', JSON_ARRAY('正确设未知数 2 分', '列出比例关系 4 分', '计算过程正确 2 分', '结果与答语完整 2 分'), JSON_ARRAY('比例', '应用题建模', '方程求解'), '设需要 x 千克，3/5 = x/40，5x = 120，x = 24。答需要 24 千克。', '/mock/student-answer-q15.png', 8, '建模和计算结果正确，但比例式书写不够规范，缺少单位换算说明。', JSON_ARRAY('核心步骤完整', '建议扣除书写规范 1 分', '答语完整，可保留 1 分'), 86, 'pending'),
		('review_002', 'sub_002', 'q_018', '六年级数学期中卷', '李四', '六年级 3 班', '18', 8, '根据面积公式拆分图形并计算。', JSON_ARRAY('图形拆分正确 3 分', '公式使用正确 3 分', '计算结果正确 2 分'), JSON_ARRAY('几何面积'), '把图形看成长方形和三角形，长方形面积 36，三角形面积 12，总面积 48。', '/mock/student-answer-q18.png', 6, '思路基本正确，但少写一个关键单位，图形拆分说明不完整。', JSON_ARRAY('公式基本正确', '拆分依据需要补充', '建议教师复核单位'), 78, 'pending')`,
	`INSERT IGNORE INTO wrong_questions
		(student_id, question_id, submission_id, question_no, knowledge_point, error_type, wrong_reason, source_paper, original_question, score, max_score, correct_answer, student_answer, answer_image_url, explanation, correction_status, repractice_status)
	VALUES
		('stu_002', 'q_001', 'sub_002', '1', '分数', 'concept', '标准答案为 A，学生选择 B', '六年级数学期中卷', '比较两个分数的大小，选择正确答案。', 0, 2, 'A', 'B', '/mock/student-answer-q18.png', '回顾分数大小比较方法。', 'pending', 'not_assigned'),
		('stu_001', 'q_015', 'sub_001', '15', '比例', 'expression', '比例关系书写不规范', '六年级数学期中卷', '根据比例关系解决实际问题。', 8, 10, '设未知数并列比例求解，结果为 24 千克。', '3/5 = x/40，x = 24。', '/mock/student-answer-q15.png', '建模正确，补充规范比例式和单位说明。', 'pending', 'not_assigned'),
		('stu_002', 'q_018', 'sub_002', '18', '几何面积', 'calculation', '图形拆分后面积计算不完整', '六年级数学期中卷', '将组合图形拆分后计算总面积。', 6, 8, '长方形与三角形面积相加。', '长方形面积 36，三角形面积 12。', '/mock/student-answer-q18.png', '标出拆分依据并写完整单位。', 'pending', 'not_assigned')`,
	`UPDATE wrong_questions wq JOIN knowledge_points kp ON kp.name = wq.knowledge_point AND kp.subject = '数学' SET wq.knowledge_point_id = kp.id WHERE wq.knowledge_point_id = ''`,
	`INSERT IGNORE INTO wrong_question_knowledge_points (wrong_question_id, knowledge_point_id, knowledge_point_name)
		SELECT wq.id, kp.id, kp.name
		FROM wrong_questions wq
		JOIN knowledge_points kp ON kp.name = wq.knowledge_point AND kp.subject = '数学'`,
	`INSERT IGNORE INTO knowledge_mastery_history (class_name, student_id, knowledge_point, mastery, wrong_count, student_count, recorded_at) VALUES
		('六年级 3 班', '', '分数应用题', 38, 32, 18, '2026-05-01'),
		('六年级 3 班', '', '分数应用题', 42, 29, 16, '2026-06-01'),
		('六年级 3 班', '', '几何面积', 57, 24, 14, '2026-05-01'),
		('六年级 3 班', '', '几何面积', 51, 21, 13, '2026-06-01'),
		('六年级 3 班', '', '比例换算', 59, 18, 11, '2026-05-01'),
		('六年级 3 班', '', '比例换算', 64, 15, 9, '2026-06-01')`,
	`INSERT IGNORE INTO exam_scores (student_name, class_name, paper_name, score, exam_at) VALUES
		('张三', '六年级 3 班', '六年级数学期中卷', 85, '2026-06-01'),
		('李四', '六年级 3 班', '六年级数学期中卷', 72, '2026-06-01'),
		('赵六', '六年级 3 班', '六年级数学期中卷', 88, '2026-06-01'),
		('王五', '六年级 3 班', '六年级数学期中卷', 82, '2026-06-01')`,
	`INSERT IGNORE INTO question_stats (paper_name, question_no, question_type, accuracy) VALUES
		('六年级数学期中卷', '1', '单选题', 96),
		('六年级数学期中卷', '8', '填空题', 82),
		('六年级数学期中卷', '15', '应用题', 42),
		('六年级数学期中卷', '18', '应用题', 38)`,
	`INSERT IGNORE INTO knowledge_stats (name, accuracy, wrong_count) VALUES
		('分数应用题', 42, 29),
		('几何面积', 51, 21),
		('比例换算', 64, 15),
		('计算基础', 88, 6)`,
	`INSERT IGNORE INTO student_risks (student_name, risk, weakness_json) VALUES
		('李四', '连续 3 次未提交作业', JSON_ARRAY('分数应用题', '比例')),
		('赵六', '本次低于班均 18 分', JSON_ARRAY('几何面积'))`,
	`INSERT IGNORE INTO homework_watch (student_name, class_name, missing, guardian) VALUES
		('李四', '六年级 3 班', 3, '李四家长'),
		('赵六', '六年级 3 班', 2, '赵六家长')`,
	`INSERT IGNORE INTO object_files (object_key, bucket, storage_driver, url, content_type, size_bytes, purpose, owner_type, owner_id, metadata_json) VALUES
		('mock/templates/tpl_001-blank-paper.pdf', 'local-dev', 'local', '/mock/templates/tpl_001-blank-paper.pdf', 'application/pdf', 0, 'template_source', 'template', 'tpl_001', JSON_OBJECT('fixture', TRUE)),
		('mock/student-answer-q15.png', 'local-dev', 'local', '/mock/student-answer-q15.png', 'image/png', 0, 'student_answer', 'submission', 'sub_001', JSON_OBJECT('fixture', TRUE)),
		('mock/student-answer-q18.png', 'local-dev', 'local', '/mock/student-answer-q18.png', 'image/png', 0, 'student_answer', 'submission', 'sub_002', JSON_OBJECT('fixture', TRUE))`,
}
